name: Cello Yoga
favicon: null
layout_spectrum: 0
typography_spectrum: 0.75508
title: Cello Yoga
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7f7f7f'
    - '#fefefe'
    - '#f4d8d2'
    - '#e6978a'
    - '#a0a7aa'
  brandStrength: 1
  lightness: 1
  saturation: 0.9375
  rhythmicContrast: 0.9241984570398927
purpose: []
