title: Cello Yoga
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9375
  brandStrength: 0
  rhythmicContrast: 0.9241984570398927
  brandColors:
    - '#7f7f7f'
    - '#fefefe'
    - '#f4d8d2'
    - '#e6978a'
    - '#a0a7aa'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Cello Yoga
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.537594
layout_spectrum: 0.2325456
